mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liuyang?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: liuyang
    password: liuyang
    driver-class-name: com.mysql.cj.jdbc.Driver
